/**
 * Per-concern env-file generators for the multi-file workspace env layout
 * (groundnuty/macf#342). PR-A of a 4-PR sequence:
 *
 *   PR-A (this PR)  — pure generators only; no init/update wiring
 *   PR-B            — refactor claude.sh to source the per-concern files
 *                     + wire writers into init/update
 *   PR-C            — migration: detect legacy monolithic claude.sh +
 *                     compat with settings.local.json env block
 *   PR-D            — operator docs
 *
 * Each generator takes a `MacfAgentConfig` and returns the textual content
 * for one per-concern env file written under `<workspace>/.claude/.macf/`.
 *
 * Concern boundaries (operator-managed vs macf-managed) come from #342:
 *   env.identity   — macf-managed   — identity vars (set BEFORE tmux self-wrap)
 *   env.github     — macf-managed   — App creds + GH_TOKEN mint + git ident
 *                                     (EMPTY in local-mode per DR-024)
 *   env.certs      — macf-managed   — cert + log paths
 *   env.registry   — macf-managed   — MACF_REGISTRY_TYPE + per-type vars
 *   env.telemetry  — operator-managed — OTel gates + endpoint
 *                                       (MINIMAL when MACF_OTEL_DISABLED=1)
 *   env.tmux       — operator-managed — MACF_TMUX_SESSION + MACF_TMUX_WINDOW
 *                                       (MINIMAL when neither set in config)
 *
 * **Pure functions** — no file I/O, no side effects. Disk writes land in
 * PR-B's `writeEnvFiles()` helper.
 *
 * **Faithful reproduction** — each generator emits the SAME export-line
 * shapes as the existing monolithic `claude-sh.ts`. The per-concern logic
 * is duplicated here rather than imported from `claude-sh.ts` because the
 * existing helpers (`registryEnvLines`, `caPathLines`,
 * `githubAppEnvLines`, `githubTokenAndIdentityLines`) are file-private.
 * PR-B will extract a shared util module and dedup.
 *
 * **Schema versioning** — each emitted file carries a `# schema_version: 1`
 * comment near the top so PR-C's migration tool (and any future bumps) can
 * detect the format version without parsing.
 */
import type { MacfAgentConfig } from './config.js';

// ---------------------------------------------------------------------------
// Headers
// ---------------------------------------------------------------------------

/**
 * Header text for macf-managed files. Mirrors the warning shape in
 * `claude-sh.ts`'s `MANAGED_HEADER_LINES` so operators see consistent
 * "do not edit" framing across all generated files. Edit the canonical
 * generator and re-run `macf update`.
 */
function managedHeaderLines(generator: string): string[] {
  return [
    '# This file is managed by `macf`. Do not edit directly — edits are',
    '# overwritten on the next `macf update`. The template lives at',
    `# groundnuty/macf:src/cli/env-files.ts (\`${generator}\`). To change`,
    '# the generated content, file an issue or PR against that file, then',
    '# run `macf update` here.',
    '#',
    '# This file is sourced (not executed) by claude.sh; vars use `export`',
    '# so they propagate to claude\'s child processes.',
  ];
}

/**
 * Header text for operator-managed files. Softer wording than the macf-
 * managed variant — operators are free to edit, and `macf update`
 * preserves their changes (PR-B + PR-C wire that contract; this file just
 * declares the intent in the header).
 */
function operatorHeaderLines(generator: string): string[] {
  return [
    `# This file is operator-editable. \`macf update\` will preserve your`,
    `# edits as long as the file exists; the canonical default content`,
    `# is generated by ${generator} in groundnuty/macf:src/cli/env-files.ts`,
    '# and re-emitted only when the file is missing entirely.',
    '#',
    '# This file is sourced (not executed) by claude.sh; vars use `export`',
    '# so they propagate to claude\'s child processes.',
  ];
}

const SCHEMA_VERSION_LINE = '# schema_version: 1';

/**
 * Assemble final file content from header + body lines. Joins with `\n`
 * and ensures trailing newline. The schema_version line goes right after
 * the header so it's the first non-comment-block content.
 */
function assemble(
  header: readonly string[],
  body: readonly string[],
): string {
  return [
    ...header,
    SCHEMA_VERSION_LINE,
    '',
    ...body,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Local-mode + path helpers (mirrored from claude-sh.ts; PR-B dedup target)
// ---------------------------------------------------------------------------

/**
 * True when this config runs in local-registry mode (DR-024 / macf#322).
 * Mirrored from `claude-sh.ts`'s file-private `isLocalMode`.
 */
function isLocalMode(cfg: MacfAgentConfig): boolean {
  return cfg.registry.type === 'local';
}

/**
 * Compute POSIX-style dirname without pulling in node:path. Mirrored from
 * `claude-sh.ts`'s file-private `posixDirname`. The launcher always runs
 * on POSIX-shaped filesystems (DR-024 §threat model).
 */
function posixDirname(p: string): string {
  const idx = p.lastIndexOf('/');
  if (idx < 0) return '.';
  if (idx === 0) return '/';
  return p.slice(0, idx);
}

// ---------------------------------------------------------------------------
// env.identity — macf-managed
// ---------------------------------------------------------------------------

/**
 * Generate `.claude/.macf/env.identity` content.
 *
 * The 5 identity vars currently set BEFORE the tmux self-wrap in
 * `claude-sh.ts`:
 *
 *   MACF_WORKSPACE_DIR  — absolute path to the workspace (cross-repo cwd
 *                          safety, see #161 + coordination.md)
 *   MACF_PROJECT        — project name
 *   MACF_AGENT_NAME     — agent identifier (with 3-layer settings priority)
 *   MACF_AGENT_ROLE     — agent role (with 3-layer settings priority)
 *   MACF_AGENT_TYPE     — `permanent` | `worker`
 *
 * MACF_AGENT_NAME and MACF_AGENT_ROLE preserve the post-#313 settings-driven
 * 3-layer priority (env > settings.local.json > baked default). Reading
 * settings.local.json requires the `macf_settings_get` helper, which is
 * defined in this file (so env.identity is self-contained when sourced
 * standalone).
 *
 * **Note on SCRIPT_DIR**: `MACF_WORKSPACE_DIR=$SCRIPT_DIR` requires that
 * the sourcing script (claude.sh in PR-B) sets SCRIPT_DIR before sourcing.
 * That contract is documented in PR-B's claude.sh refactor; this file
 * trusts it.
 */
export function generateEnvIdentity(config: MacfAgentConfig): string {
  const body = [
    `# Generator: generateEnvIdentity (env-files.ts)`,
    `# Sourced by claude.sh BEFORE the tmux self-wrap so identity vars are`,
    `# present in the env captured by the \`-e VAR=VAL\` pass-through (macf#340).`,
    '',
    '# Settings-driven identity helper (macf#313). Reads `.env.<NAME>` from',
    '# .claude/settings.local.json via jq; returns empty string if file/key',
    '# missing or jq absent. Identity-override block uses it to prefer',
    '# operator-edited settings.local.json over baked defaults, without',
    '# forcing operators to edit this generated file.',
    'macf_settings_get() {',
    '  local var_name="$1"',
    '  if [ -f "$SCRIPT_DIR/.claude/settings.local.json" ] && command -v jq >/dev/null 2>&1; then',
    '    jq -r ".env.${var_name} // empty" "$SCRIPT_DIR/.claude/settings.local.json" 2>/dev/null',
    '  fi',
    '}',
    '',
    '# Cross-repo path resolution (#140 + #161). Runtime templates reference',
    '# $MACF_WORKSPACE_DIR for absolute-path commands so cd-ing to another',
    '# repo doesn\'t break helper invocations.',
    'export MACF_WORKSPACE_DIR="$SCRIPT_DIR"',
    `export MACF_PROJECT="${config.project}"`,
    `export MACF_AGENT_TYPE="${config.agent_type}"`,
    '',
    '# Settings-driven identity overrides (macf#313). Three-layer priority:',
    '#   1. Already-set env var (operator: `MACF_AGENT_NAME=foo ./claude.sh`)',
    '#   2. .claude/settings.local.json `env` block',
    '#   3. Baked default from macf init/update (this generated file)',
    `MACF_AGENT_NAME="\${MACF_AGENT_NAME:-$(macf_settings_get MACF_AGENT_NAME)}"`,
    `MACF_AGENT_NAME="\${MACF_AGENT_NAME:-${config.agent_name}}"`,
    'export MACF_AGENT_NAME',
    `MACF_AGENT_ROLE="\${MACF_AGENT_ROLE:-$(macf_settings_get MACF_AGENT_ROLE)}"`,
    `MACF_AGENT_ROLE="\${MACF_AGENT_ROLE:-${config.agent_role}}"`,
    'export MACF_AGENT_ROLE',
  ];
  return assemble(managedHeaderLines('generateEnvIdentity'), body);
}

// ---------------------------------------------------------------------------
// env.github — macf-managed; EMPTY in local-mode
// ---------------------------------------------------------------------------

/**
 * Generate `.claude/.macf/env.github` content.
 *
 * Emits APP_ID / INSTALL_ID / KEY_PATH App-cred exports + the relative-
 * path resolver + the fail-loud `macf-gh-token.sh` invocation + git
 * author/committer name exports.
 *
 * **Empty placeholder in local-mode** (cfg.registry.type === 'local',
 * DR-024). The body is just the header + schema_version + a comment
 * explaining why — no GitHub App tokens are minted in local-registry
 * mode (commits land as the local user, not as `app/<bot>[bot]`). The
 * absence of GH_TOKEN-mint logic is what makes local-mode work without
 * GitHub credentials.
 */
export function generateEnvGitHub(config: MacfAgentConfig): string {
  if (isLocalMode(config)) {
    const body = [
      '# Generator: generateEnvGitHub (env-files.ts)',
      '#',
      '# Intentionally empty for local-mode workspace. Per DR-024 / macf#322,',
      '# local-registry mode does not mint a GitHub App installation token —',
      '# coordination uses the local registry file at $MACF_REGISTRY_PATH, and',
      '# commits land as the local user (not as `app/<bot>[bot]`). No APP_ID,',
      '# INSTALL_ID, KEY_PATH, GH_TOKEN, or GIT_AUTHOR_NAME/GIT_COMMITTER_NAME',
      '# are exported. See DR-024 §"Routing trade-offs".',
      `echo "Starting ${config.agent_name} (${config.agent_role}) [local-registry mode]..."`,
    ];
    return assemble(managedHeaderLines('generateEnvGitHub'), body);
  }

  const githubApp = config.github_app;
  // Defensive — schema marks github_app optional, but non-local mode
  // requires it (init.ts enforces the pairing at write time per
  // config.ts comments). If it's missing here, the workspace config is
  // broken; surface that visibly rather than emitting partial exports.
  if (!githubApp) {
    const body = [
      '# Generator: generateEnvGitHub (env-files.ts)',
      '#',
      '# WARNING: this workspace config has registry.type !== "local" but no',
      '# `github_app` block. Re-run `macf init --force` to repair.',
    ];
    return assemble(managedHeaderLines('generateEnvGitHub'), body);
  }

  const body = [
    '# Generator: generateEnvGitHub (env-files.ts)',
    '',
    '# GitHub App credentials. KEY_PATH is resolved against $SCRIPT_DIR if',
    '# relative (cross-repo cwd safety per #140 + #161 — without this, cd-ing',
    '# to another repo breaks the token helper and triggers the attribution',
    '# trap).',
    `export APP_ID="${githubApp.app_id}"`,
    `export INSTALL_ID="${githubApp.install_id}"`,
    `export KEY_PATH="${githubApp.key_path}"`,
    'case "$KEY_PATH" in',
    '  /*) ;;  # already absolute',
    '  *) KEY_PATH="$SCRIPT_DIR/$KEY_PATH" ;;',
    'esac',
    'export KEY_PATH',
    '',
    '# Bot token generation — fail loud. The helper validates the ghs_ prefix',
    '# and surfaces diagnostics (clock drift, bad key, wrong App/install ID).',
    '# Do NOT inline the bare CLI here — without pipefail, a failed fetch piped',
    '# through jq would succeed, GH_TOKEN would become "null", and Claude Code',
    '# would silently fall back to stored `gh auth login` as the user. See the',
    '# attribution-trap section of coordination.md Token & Git Hygiene.',
    'GH_TOKEN=$("$SCRIPT_DIR/.claude/scripts/macf-gh-token.sh" \\',
    '    --app-id "$APP_ID" --install-id "$INSTALL_ID" --key "$KEY_PATH") || {',
    '  echo "FATAL: bot token generation failed — see stderr above." >&2',
    '  exit 1',
    '}',
    'export GH_TOKEN',
    '',
    `export GIT_AUTHOR_NAME="${config.agent_name}[bot]"`,
    `export GIT_COMMITTER_NAME="${config.agent_name}[bot]"`,
    '',
    `echo "Starting ${config.agent_name} (${config.agent_role})..."`,
  ];
  return assemble(managedHeaderLines('generateEnvGitHub'), body);
}

// ---------------------------------------------------------------------------
// env.certs — macf-managed
// ---------------------------------------------------------------------------

/**
 * Generate `.claude/.macf/env.certs` content.
 *
 * CA + agent cert paths + log path. Local-mode CAs live next to the
 * registry file (`~/.macf/registry/<project>.ca.{crt,key}`), GitHub-mode
 * CAs live under `~/.macf/certs/<project>/`. Both modes need
 * MACF_CA_CERT/MACF_CA_KEY exported for channel-server mTLS.
 */
export function generateEnvCerts(config: MacfAgentConfig): string {
  const lines: string[] = [
    '# Generator: generateEnvCerts (env-files.ts)',
    '',
  ];

  if (isLocalMode(config)) {
    // Pre-resolve the local-registry directory at template time so the
    // generated file doesn't need to expand `~`. Tilde already resolved
    // in cfg.registry.path (init.ts uses os.homedir()).
    const registryPath =
      config.registry.type === 'local' ? config.registry.path : '';
    const registryDir = posixDirname(registryPath);
    lines.push(
      `export MACF_CA_CERT="${registryDir}/${config.project}.ca.crt"`,
      `export MACF_CA_KEY="${registryDir}/${config.project}.ca.key"`,
    );
  } else {
    lines.push(
      `export MACF_CA_CERT="$HOME/.macf/certs/${config.project}/ca-cert.pem"`,
      `export MACF_CA_KEY="$HOME/.macf/certs/${config.project}/ca-key.pem"`,
    );
  }

  lines.push(
    'export MACF_AGENT_CERT="$SCRIPT_DIR/.macf/certs/agent-cert.pem"',
    'export MACF_AGENT_KEY="$SCRIPT_DIR/.macf/certs/agent-key.pem"',
    'export MACF_LOG_PATH="$SCRIPT_DIR/.macf/logs/channel.log"',
  );

  return assemble(managedHeaderLines('generateEnvCerts'), lines);
}

// ---------------------------------------------------------------------------
// env.registry — macf-managed
// ---------------------------------------------------------------------------

/**
 * Generate `.claude/.macf/env.registry` content.
 *
 * MACF_REGISTRY_TYPE + per-type vars. Mirrors `claude-sh.ts`'s
 * `registryEnvLines` exhaustive switch (so a new RegistryConfig variant
 * fails the build here too, forcing a paired update).
 */
export function generateEnvRegistry(config: MacfAgentConfig): string {
  const body: string[] = [
    '# Generator: generateEnvRegistry (env-files.ts)',
    '#',
    '# The plugin\'s src/config.ts reads MACF_REGISTRY_TYPE + per-type vars',
    '# on startup; without them the plugin falls back to a hardcoded default',
    '# repo and 403s every registry op on consumers in other scopes.',
    '# See macf#178.',
    '',
  ];

  switch (config.registry.type) {
    case 'repo':
      body.push(
        `export MACF_REGISTRY_TYPE="repo"`,
        `export MACF_REGISTRY_REPO="${config.registry.owner}/${config.registry.repo}"`,
      );
      break;
    case 'org':
      body.push(
        `export MACF_REGISTRY_TYPE="org"`,
        `export MACF_REGISTRY_ORG="${config.registry.org}"`,
      );
      break;
    case 'profile':
      body.push(
        `export MACF_REGISTRY_TYPE="profile"`,
        `export MACF_REGISTRY_USER="${config.registry.user}"`,
      );
      break;
    case 'local':
      body.push(
        `export MACF_REGISTRY_TYPE="local"`,
        `export MACF_REGISTRY_PATH="${config.registry.path}"`,
      );
      break;
  }

  return assemble(managedHeaderLines('generateEnvRegistry'), body);
}

// ---------------------------------------------------------------------------
// env.telemetry — operator-managed; MINIMAL when MACF_OTEL_DISABLED=1
// ---------------------------------------------------------------------------

/**
 * Generate `.claude/.macf/env.telemetry` content.
 *
 * The 3 OTel mandatory gates + per-signal exporters + endpoint resolution.
 * Mirrors `claude-sh.ts`'s `otelTelemetryLines` (including the same
 * shell-unsafe-char rejection on MACF_OTEL_ENDPOINT and the same default
 * endpoint `http://localhost:14318` per macf-devops-toolkit canonical k3d
 * topology).
 *
 * **Minimal placeholder when `MACF_OTEL_DISABLED=1`** (operator opt-out at
 * template-time per macf#197). Body shrinks to header + schema_version +
 * a comment explaining the opt-out — no OTel exports emitted, so sourcing
 * the file is a no-op.
 *
 * @param env — defaults to `process.env`; tests inject a fake.
 */
export function generateEnvTelemetry(
  config: MacfAgentConfig,
  env: NodeJS.ProcessEnv = process.env,
): string {
  if (env['MACF_OTEL_DISABLED'] === '1' || env['MACF_OTEL_DISABLED'] === 'true') {
    const body = [
      '# Generator: generateEnvTelemetry (env-files.ts)',
      '#',
      '# Telemetry intentionally disabled (MACF_OTEL_DISABLED=1 at',
      '# `macf init` / `macf update` time). No OTel exporters or gates',
      '# are configured; sourcing this file is a no-op. See macf#197.',
      '#',
      '# To re-enable: re-run `macf update` without MACF_OTEL_DISABLED set.',
    ];
    return assemble(operatorHeaderLines('generateEnvTelemetry'), body);
  }

  const endpoint = env['MACF_OTEL_ENDPOINT'] ?? 'http://localhost:14318';

  // Same allowlist pattern as otelTelemetryLines in claude-sh.ts. The
  // endpoint value gets embedded verbatim in a shell double-quoted export.
  if (/["$`\\\n\r]/.test(endpoint)) {
    throw new Error(
      `MACF_OTEL_ENDPOINT contains a shell-unsafe character. ` +
        `Got: ${JSON.stringify(endpoint)}. ` +
        `Expected a plain URL like http://host:port.`,
    );
  }

  const body = [
    '# Generator: generateEnvTelemetry (env-files.ts)',
    '#',
    '# Claude Code native OTEL telemetry → observability stack',
    '# (macf#197 + macf#245). Three telemetry signal gates — each',
    '# independent, ALL required for the corresponding signal to emit:',
    '#   CLAUDE_CODE_ENABLE_TELEMETRY        — master telemetry gate',
    '#   CLAUDE_CODE_ENHANCED_TELEMETRY_BETA — additional gate for traces',
    '#   OTEL_TRACES_EXPORTER=otlp           — emit traces',
    '#   OTEL_METRICS_EXPORTER=otlp          — emit metrics',
    '#   OTEL_LOGS_EXPORTER=otlp             — emit logs',
    '# Without the per-signal exporter env vars, that signal silently emits',
    '# nothing even if the master gate is on (#245 surfaced the metrics+logs',
    '# gap — only traces had the exporter set; metrics + logs were dark).',
    '#',
    '# Endpoint override has two layers (groundnuty/macf#282):',
    '#   - Template-time: MACF_OTEL_ENDPOINT=<url> at `macf init` /',
    '#     `macf update` bakes a different default into this file',
    '#   - Run-time: OTEL_EXPORTER_OTLP_ENDPOINT=<url> in the shell',
    '#     BEFORE invoking ./claude.sh overrides the baked default',
    'export CLAUDE_CODE_ENABLE_TELEMETRY=1',
    'export CLAUDE_CODE_ENHANCED_TELEMETRY_BETA=1',
    'export OTEL_TRACES_EXPORTER=otlp',
    'export OTEL_METRICS_EXPORTER=otlp',
    'export OTEL_LOGS_EXPORTER=otlp',
    // 4-layer endpoint resolution chain (macf#313). Requires
    // macf_settings_get to be defined upstream — env.identity defines it,
    // and PR-B's claude.sh sources env.identity before env.telemetry.
    `MACF_OTEL_ENDPOINT="\${MACF_OTEL_ENDPOINT:-$(macf_settings_get MACF_OTEL_ENDPOINT)}"`,
    `MACF_OTEL_ENDPOINT="\${MACF_OTEL_ENDPOINT:-${endpoint}}"`,
    'export OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT:-$MACF_OTEL_ENDPOINT}"',
    'export OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf',
    `export OTEL_SERVICE_NAME="macf-agent-${config.agent_name}"`,
    `export OTEL_RESOURCE_ATTRIBUTES="gen_ai.agent.name=${config.agent_name},gen_ai.agent.role=${config.agent_role},service.namespace=macf"`,
  ];
  return assemble(operatorHeaderLines('generateEnvTelemetry'), body);
}

// ---------------------------------------------------------------------------
// env.tmux — operator-managed; MINIMAL when neither tmux_session nor _window set
// ---------------------------------------------------------------------------

/**
 * Generate `.claude/.macf/env.tmux` content.
 *
 * MACF_TMUX_SESSION + MACF_TMUX_WINDOW for the on-notify wake path
 * (macf#185). When the channel server's onNotify handler fires, it shells
 * out to `tmux-send-to-claude.sh <session>:<window> <prompt>` to inject
 * the notification as the TUI's next input turn.
 *
 * **Minimal placeholder when neither field is set in config.** The wake
 * path falls back to auto-detect from $TMUX in that case (existing
 * behavior — no env var needed). Avoids generating an empty-export file.
 */
export function generateEnvTmux(config: MacfAgentConfig): string {
  const hasSession = config.tmux_session !== undefined;
  const hasWindow = config.tmux_window !== undefined;

  if (!hasSession && !hasWindow) {
    const body = [
      '# Generator: generateEnvTmux (env-files.ts)',
      '#',
      '# No MACF_TMUX_SESSION or MACF_TMUX_WINDOW configured for this agent.',
      '# The on-notify wake path (macf#185) auto-detects from $TMUX when the',
      '# channel server is launched inside a tmux pane; otherwise no-ops',
      '# silently. To target a specific named pane (e.g., agent launched',
      '# outside tmux by a supervisor), set tmux_session / tmux_window in',
      '# `.macf/macf-agent.json` and re-run `macf update`.',
    ];
    return assemble(operatorHeaderLines('generateEnvTmux'), body);
  }

  const body: string[] = [
    '# Generator: generateEnvTmux (env-files.ts)',
    '#',
    '# tmux session:window for the on-notify wake path (macf#185). The',
    '# channel server\'s onNotify handler shells out to tmux-send-to-claude.sh',
    '# <session>:<window> <prompt> to inject notifications into the TUI.',
    '',
  ];
  if (hasSession) {
    body.push(`export MACF_TMUX_SESSION="${config.tmux_session}"`);
  }
  if (hasWindow) {
    body.push(`export MACF_TMUX_WINDOW="${config.tmux_window}"`);
  }
  return assemble(operatorHeaderLines('generateEnvTmux'), body);
}
